config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :consoles, only: [:index, :show, :new, :create, :edit, :update] do
    resources :bookings, only: [:new, :create]
    # resources :reviews ,only: [:new, :create]
  end
  resources :bookings, only: [ :show, :edit, :update ] do
    resources :reviews, only: [ :new, :create ]
  end
  # get "/bookings/:booking_id/reviews/new", to: 'reviews#new'
  # post "/bookings/:booking_id/reviews", to: 'reviews#create'
  get "/dashboards", to: "bookings#index", as: :dashboards
  # get "/dashboards", to: "dashboards#bk_renter", as: :dash_renter
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :console
  has_many :reviews

  validates :start_date, :end_date, presence: true
end

app/models/console.rb
class Console < ApplicationRecord
  belongs_to :user
  has_many :bookings
  has_many :reviews, through: :bookings

  validates :brand, :model, :description, :address, :price, :number_of_pads, presence: true

  mount_uploader :photo, PhotoUploader

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :booking

  validates :rating, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :consoles
  has_many :bookings_on_consoles, through: :consoles, source: :bookings
  has_many :bookings
  has_many :booked_consoles, through: :bookings, source: :console

  # validates :avatar, presence: true
  mount_uploader :avatar, PhotoUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  include Pundit

  # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end

  # [...]
  private

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :password, :email, :avatar])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end



  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  def index
    @bookings = policy_scope(Booking)
  end

  def new
    @booking = Booking.new
    authorize @booking
    @console = Console.find(params[:console_id])
  end

  def create
    @console = Console.find(params[:console_id])
    @booking = Booking.new(booking_params)
    @booking.console = @console
    @booking.user = current_user
    authorize @booking
    if @booking.save
      redirect_to dashboards_path
    else
      render :new
    end
  end

  def edit
    @booking = Booking.find(params[:id])
    authorize @booking
  end

  def update
    @booking = Booking.find(params[:id])
    authorize @booking
 # raise
    if params[:booking][:status].present?
      @booking.update(status: params[:booking][:status])
      redirect_to dashboards_path, notice: "bookings updated"
    else
      if @booking.update(booking_params)
        redirect_to dashboards_path
      else
        render :new
      end
    end
  end



 private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date)
  end
end

app/controllers/consoles_controller.rb
class ConsolesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]
  def index
    @consoles = policy_scope(Console)
    @consoles = Console.where(brand: params[:console][:brand]) if (params[:console].present? && params[:console][:brand].present?)
    @consoles = Console.where(model: params[:console][:model]) if (params[:console].present? && params[:console][:model].present?)

    # @consoles = Console.where.not(latitude: nil, longitude: nil)

    @markers = @consoles.map do |console|
       {
         lat: console.latitude,
         lng: console.longitude,
         icon: ActionController::Base.helpers.asset_path('Mario_pixel.png'),
         infoWindow: { content: render_to_string(partial: "/consoles/shared/map_box", locals: { console: console }) }
       }
    end
  end

  def show
    @console = Console.find(params[:id])
    @booking = Booking.new
    authorize @console
  end

  def new
    @brands = Console.distinct.pluck(:brand)
    @models = Console.distinct.pluck(:model)
    @console = Console.new
    authorize @console
  end

  def create
    @console = Console.new(console_params)
    @console.user = current_user
    authorize @console
    if @console.save
      redirect_to consoles_path
    else
      render :new
    end
  end

  def edit
    @console = Console.find(params[:id])
    authorize @console
  end

  def update
    @console = Console.find(params[:id])
    authorize @console
    if @console.update(console_params)
      redirect_to root_path
    else
      render :new
    end
  end

  private

  def console_params
    params.require(:console).permit(:brand, :model, :number_of_pads, :description, :address, :price, :photo)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
    @brands = Console.distinct.pluck(:brand)
    @models = Console.distinct.pluck(:model)
    @console = Console.new
    authorize @console
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def new
    @booking = Booking.find(params[:booking_id])
    # @console = @booking.console
    @review = @booking.reviews.new
    # @booking = Booking.find_by(user_id: current_user)
    authorize @review
  end

  def create
    @booking = Booking.find(params[:booking_id])


    # @console = Console.find(params[:console_id])
    @review = Review.new(review_params)
    @review.booking = @booking
    authorize @review
    if @review.save
      redirect_to consoles_path
    else
      render :new
    end
  end

  private

  def review_params
    params.require(:review).permit(:description, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/index.html.erb
<div class="wrapper">
  <div class="container">




    <h1>dashboard <i class="fas fa-trophy"></i></h1>

     <h1>Mes bookings (<%= current_user.bookings.count %>)</h1>
    <% current_user.bookings.each do |book| %>

<div class="message">
   <%= cl_image_tag book.console.user.avatar, class: "avatar-large" %>
  <div class="message-name">
    <h3><i class="fas fa-terminal"></i><%=book.console.user.email %></h3>
  </div>
  <div class="message-body">
    <p>
    <strong> <%= book.console.brand %> <%= book.console.model %></strong> du <%= book.start_date %> au <%= book.end_date %>
    </p>
  </div>

  <% if book.status == "Pending" %>
  <i class="fas fa-question" style="color:blue"></i>
<% elsif book.status == "accepted" %>
             <i class="far fa-check-circle" style="color:green"></i>
<% else %>
                <i class="fas fa-ban" style="color:Tomato"></i>
<% end %>



</div>

    <% end %>


    <hr>

<div class="encart-dash">
 <h1>Mes consoles en location (<%= current_user.bookings_on_consoles.count %>)</h1>
    <% current_user.bookings_on_consoles.each do |book| %>

<div class="message">
   <%= cl_image_tag book.user.avatar, class: "avatar-large" %>
  <div class="message-name">
    <h3><i class="fas fa-terminal"></i><%=book.user.email %></h3>
  </div>
  <div class="message-body">
    <p>
    <strong> <%= book.console.brand %> <%= book.console.model %></strong> du <%= book.start_date %> au <%= book.end_date %>
    </p>
  </div>
        <div class="buttons-container">
        <% if policy(book).edit? && book.status == "Pending"%>
        <%= simple_form_for book do |f| %>
        <%= f.input :status, as: :hidden, input_html: { value: 'accepted'} %>
        <%= f.submit "Accepted", class: "btn-green" %>
        <% end %>
        <%= simple_form_for book do |f| %>
        <%= f.input :status, as: :hidden, input_html: { value: 'Rejected'} %>
        <%= f.submit "Refuser", class: "btn-yellow" %>
        <% end %>
        <% end %>
      </div>

<% if book.status == "Pending" %>
<% elsif book.status == "accepted" %>
             <i class="far fa-check-circle" style="color:green"></i>
<% else %>
                <i class="fas fa-ban" style="color:Tomato"></i>
<% end %>






</div>

    <% end %>

</div>
  </div>
</div>

app/views/bookings/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-6 col-sm-offset-3">
      <h1>New booking</h1>
        <div>
      <%= simple_form_for [@console, @booking] do |f| %>
      <%= f.label "Début de la location" %>
      <%= f.date_field :start_date %>
      <%= f.label "Fin de la location" %>
      <%= f.date_field :end_date  %>
        </div>
      <%= f.submit "Louer", class: "btn btn-danger" %>
      <% end %>
    </div>
  </div>
</div>

app/views/consoles/edit.html.erb
<div class="wrapper2">
  <div class="container">
    <div class="black-card">
      <div class="row">
        <div class="col-md-6">
          <div class="title">
            <h1 class="text-center">Edit your Gaming Console</h1>
          </div>
        </div>
        <div class="col-md-4 col-md-offset-1">
          <% if @console.errors.any? %>
              <div class="errors-container">
                <ul>
                  <% @console.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                  <% end %>
                </ul>
              </div>
            <% end %>
              <%= simple_form_for @console do |f| %>
              <%= f.input :brand, :collection => @brands %>
              <%= f.input :model, :collection => @models %>
              <%= f.input :number_of_pads %>
              <%= f.input :address %>
              <%= f.input :description %>
              <%= f.input :price %>
              <%= f.input :photo %>
              <%= f.input :photo_cache, as: :hidden %>
              <%= f.submit class: "btn form-control btn-primary" %>
              <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/consoles/index.html.erb
<div class="wrapper-map">
    <h1 class="text">Our Consoles</h1>
    <div class="main-container">
      <div class="card-container">
        <div class="row">
          <% @consoles.each do |console| %>
            <div class="col-xs-12 col-sm-6 col-md-4">
              <% if console.photo.present? %>
                <div class="card" style="background-image: url(
                  '<%= cl_image_path console.photo %>')">
              <% else %>
                <div class="card" style="background-image: url(assets/console_retro.jpg)">
              <% end %>
                  <h6><%= console.brand %>
                  <%= console.model %></h6>
                  <p><%= link_to console_path(console), class:"btn-yellow" do %>
                  <%= console.price %>€/Jour
                  <% end %></p>
                </div>
              </div>
            <% end %>
          </div>
        </div>
      <div
        id="map"
        style="width: 100%;
        height: 600px;"
        data-markers="<%= @markers.to_json %>"
      ></div>
    </div>
</div>

app/views/consoles/new.html.erb
<div class="wrapper2">
  <div class="container">
    <div class="black-card">
      <div class="row">
        <div class="col-md-6">
          <div class="title">
            <h1 class="text-center">Add your Gaming Console</h1>
          </div>
        </div>
        <div class="col-md-4 col-md-offset-1 padding-form ">
          <% if @console.errors.any? %>
              <div class="errors-container">
                <ul>
                  <% @console.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                  <% end %>
                </ul>
              </div>
            <% end %>
              <%= simple_form_for @console do |f| %>
              <%= f.input :brand, :collection => @brands %>
              <%= f.input :model, :collection => @models %>
              <%= f.input :number_of_pads %>
              <%= f.input :address %>
              <%= f.input :description %>
              <%= f.input :price %>
              <%= f.input :photo %>
              <%= f.input :photo_cache, as: :hidden %>
              <%= f.submit class: "btn-green btn form-control" %>
              <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/consoles/shared/_map_box.html.erb
<div class="card card-info-bulle" style="background-image: url(
  '<%= cl_image_path console.photo %>')">
</div>
<p class="card-info-bulle"><%= console.brand %> <%= console.model %></p>
<p><%= link_to console_path(console), class:"btn-yellow" do %>
<%= console.price %>€/Jour
<% end %></p>

app/views/consoles/show.html.erb
<div class="wrapper-show">
  <div class="container">
    <div class="black-card">
      <div class="row">
        <h1><%= @console.brand %> <%= @console.model %></h1>
        <div>
        <div class="col-md-6">
          <% if @console.photo.present? %>
            <div class="img-show" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= cl_image_path @console.photo, height: 300, width: 400, crop: :fill %>')">
            </div>
          <% else %>
            <!-- <div class="img-show" style="background-image: url(assets/console_retro.jpg)"> -->
              <div class="img-show" style="background-image: url('/assets/console_retro.jpg')">
            </div>
          <% end %>
          </div>
        </div>
        <div class="col-md-4 col-md-offset-1">
          <div class="description text-left">
            <p> <strong>Propriétaire</strong> : <%= @console.user.email %></p>
            <p> <strong>Description</strong> : <%= @console.description %></p>
            <p> <strong>Nombre de joueur </strong> : <%= @console.number_of_pads %> <i class="fas fa-gamepad"></i></p>
          </div>
          <hr>
           <div class= "text-left">
            <%= simple_form_for [@console, @booking] do |f| %>
            <%= f.input :start_date, as: :string, required: false, input_html: {id: "range_start"} %>
             <%= f.input :end_date, as: :string, required: false, input_html: {id: "range_end"} %>
           </div>
           <hr>
           <p>  <strong>Prix</strong>: <%= @console.price  %> Euro / jour <i class="fas fa-coins"></i></p>
            <%= f.submit "Louer", class: "btn-green" %>
      <% end %>
        </div>
        </div>
        <hr>
        <div class="text-left reviews">
          <h4>reviews</h4>
          <p><i class="fas fa-terminal"></i> trop bien</p>
          <p><i class="fas fa-terminal"></i> jamais reçu</p>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>DonkeyKong</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= render 'shared/footer' %>
    <%= javascript_pack_tag 'application' %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_include_tag "https://maps.googleapis.com/maps/api/js?libraries=places&key=#{ENV['GOOGLE_API_BROWSER_KEY']}" %>
    <%= javascript_pack_tag "map" %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="wrapper min-height">
  <div class="encart">
    <div class="container">
      <div class="row">
        <div class="col-xs-12">
          <h1 class="text-center">GAME IN PIXELS</h1>
          <div class="mario">
            <%= image_tag "Mario1.png" %>
          </div>
          <div class=" form form-inline text-center">
            <%= simple_form_for @console, method: :get do |f| %>
            <%= f.input :address, label: false, placeholder:'WHERE' %>
            <%= f.input :brand, label: false, prompt:'--', :collection => @brands %>
            <%= f.input :model, label: false, prompt:'--', :collection => @models %>
            <%= f.submit "GAME", class: "btn form-control btn-green", id:'home_search_btn' %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/reviews/new.html.erb
<h1 class="text-center">Add a review for <%= @booking.console.brand %></h1>

<div class="container">
  <div class="row">
    <div class="col-xs-6 col-xs-offset-3">
      <%= simple_form_for [@booking, @review] do |f| %>
        <%= f.input :description %>
        <%= f.input :rating %>
        <%= f.submit "Add a review", class: "btn btn-success" %>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><%= icon('fab', 'github') %></a>
    <a href="#"><%= icon('fab', 'instagram') %></a>
    <a href="#"><%= icon('fab', 'facebook') %></a>
    <a href="#"><%= icon('fab', 'twitter') %></a>
    <a href="#"><%= icon('fab', 'linkedin') %></a>

  </div>
  <div class="footer-copyright">
    This footer is made with <i class="fas fa-heart"></i> at Le Wagon
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "LOGO.png", width: 100 %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <% if user_signed_in? %>

      <!-- Links when logged in -->




        <%= link_to dashboards_path, class: "navbar-wagon-item navbar-wagon-link" do %>
        <i class="fas fa-trophy"></i> <span>Mon Dashboard</span>
        <% end %>

        <%= link_to new_console_path, class: "navbar-wagon-item navbar-wagon-link" do %>
      <i class="fas fa-hand-holding-usd"></i> <span>Je loue ma console</span>
        <% end %>


      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">

          <% if current_user.avatar %>
            <%= cl_image_tag current_user.avatar, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <% else  %>
            <%= image_tag "sonic.png", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <% end  %>

          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to edit_user_registration_path do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
              <% end %>
            </li>
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-cog"></i>  <%= t(".settings", default: "Settings") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% else %>
      <!-- Login link (when logged out) -->
      <%= link_to "Loue ta console", new_console_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>